services:
 backend:
    build: .
    ports:
     - '9000:9000'
    depends_on:
     - db
 db:
    image: postgres:lastest
    environment:
     - POSTGRES_USER = myuser
     - POSTGRES_PASSWORD = mypassword 
     - POSTGRES_DB = mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z

volumes:
  postgres_data: 
      
