services:
 backend:
    build: .
    ports:
     - '9000:9000'
    depends_on:
     - db
    environment:
     - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
     - ML_API_URL=http://ml-api:8000
 
 ml-api:
    build: ./ml-service
    ports:
     - '8000:8000'
    depends_on:
     - db 
    environment:
     - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public

 db:
    image: docker.io/pgvector/pgvector:pg16
    environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    volumes:
     - postgres_data:/var/lib/postgresql/data:Z
    ports:
    - "5433:5432"

volumes:
  postgres_data:
